
name: Update Layers

on:
  schedule:
    # weekly
    - cron:  '0 0 * * 0'
  push:
    branches:
      - master
    paths:
      - .github/workflows/update-layers.yml
  workflow_dispatch:

jobs:
  update-layers:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Update layers
        runs: |
          cd swiss_locator/map_geo_admin
          ./download_layer_data.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update map.geo.admin.ch layers
          title: Automated updates to map.geo.admin.ch layers
          body:
          branch: update-layers